### ISSUE TITLE
How long is a summary between to spec suppose to take?

### ISSUE THREAD

**Issue by WyriHaximus** [pb33f/openapi-changes#37]
Been working on a generated GitHub client based on their OpenAPI spec, and I've been looking for a tool to generate a meaningful message when a new version of a client is generated.  

To test your tool I'm currently running this command, and it's been 5 and a half hours at this point:
```bash
docker run --rm -v $PWD:/work:rw pb33f/openapi-changes summary example/api.github.com.yaml https://raw.githubusercontent.com/github/rest-api-description/main/descriptions-next/api.github.com/api.github.com.yaml
```

**Comment by daveshanley** [comment]
Certainly not 5 hours! It should take no more than a few seconds, even for huge specs.

**Comment by daveshanley** [comment]
I will look into this for you, it's hung on something.

**Comment by WyriHaximus** [comment]
It's probably that is has to download the spec. Running it with 
```
docker run --rm -v $PWD:/work:rw pb33f/openapi-changes summary https://raw.githubusercontent.com/github/rest-api-description/69b0447c7dcc7fff0fcaf9f76da1041d5ff43420/descriptions-next/api.github.com
/api.github.com.yaml https://raw.githubusercontent.com/github/rest-api-description/main/descriptions-next/api.github.com/api.github.com.yaml   
```

Fails, while downloading both files locally and running 

```
docker run --rm -v $PWD:/work:rw pb33f/openapi-changes summary api.github.com.yaml.1 api.github.com.yaml 
```

works fine.

**Comment by daveshanley** [comment]
You can re-try this command now, `openapi-changes` supports URLs now (which is why this was originally failing)

For example:

`docker run --rm -v $PWD:/work:rw pb33f/openapi-changes summary https://raw.githubusercontent.com/github/rest-api-description/69b0447c7dcc7fff0fcaf9f76da1041d5ff43420/descriptions-next/api.github.com/api.github.com.yaml https://raw.githubusercontent.com/github/rest-api-description/main/descriptions-next/api.github.com/api.github.com.yaml  `

Will generate:

```
❌  64 Breaking changes out of 2093
 INFO  Modifications: 1900
 INFO  Removals: 40
 INFO  Additions: 154
 INFO  Breaking Removals: 38
 INFO  Breaking Modifications: 4
 INFO  Breaking Additions: 22
```
After a few seconds.

**Comment by WyriHaximus** [comment]
Blazing fast now, took 3 runs, 10, 11, and 27 seconds :+1: . Thanks!
