### ISSUE TITLE
Open API Changes , install not working on Windows

### ISSUE THREAD

**Issue by LasneF** [pb33f/openapi-changes#90]
here is a diff between vacuum that works and open api change 
it should leverage tar that maintains executable statement rather than relying on chmod that looks not ok 

PS D:\tmp\developer-portal> npm i -g @pb33f/openapi-changes
npm ERR! code 1
npm ERR! path C:\Users\XXX\AppData\Roaming\npm\node_modules\@pb33f\openapi-changes
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node ./npm-install/postinstall.js
npm ERR! fetching from URL https://github.com/pb33f/openapi-changes/releases/download/v0.0.53/openapi-changes_0.0.53_windows_x86_64.zip
npm ERR! Error: ENOENT: no such file or directory, chmod './bin/openapi-changes'
npm ERR!     at Module.chmodSync (node:fs:1916:3)
npm ERR!     at install (file:///C:/Users/XXX/AppData/Roaming/npm/node_modules/@pb33f/openapi-changes/npm-install/postinstall.js:54:14)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
npm ERR!   errno: -4058,
npm ERR!   syscall: 'chmod',
npm ERR!   code: 'ENOENT',
npm ERR!   path: './bin/openapi-changes'
npm ERR! }

![image](https://github.com/pb33f/openapi-changes/assets/12461661/c1a63fe8-a4ff-4d61-9d6f-c58facbfdc36)

**Comment by daveshanley** [comment]
This is interesting, 

`openapi-changes` is actually built on a windows runner, this is because the build uses a great tool called `goreleaser` that does all the hard work of building and releasing go apps. 

The reason why it's running on windows, is because `openapi-changes` is available for windows, through 'choclatey' (https://community.chocolatey.org/packages/openapi-changes) and the only way to build a choclatey release, is to build on windows, so the whole build is performed on windows.

The very first issue I ran into when porting the build from linux to windows (to get choco support in), was that the windows runners do not have `tar` available as a command, nor gzip. The only way to build an archive, is to zip it up. 

This also applies to all windows consumers, they won't be able to unpack the `tar` archive when installing via `npm`. They will only ever see errors about `tar` not being a recognized command. 

Now this is with me doing a minimal amount of work on the build system to move things forward, however I did look up how my friends over at speakeasy distributed their CLI (https://github.com/speakeasy-api/speakeasy/blob/main/.github/workflows/release.yml) And I did the same thing. 

Can you try installing via choco? does that work OK for you?

I will think more about the permission issue as well, but I don't have a great solution off the top of my head a the moment.

**Comment by daveshanley** [comment]
The only solution I can think of it to try and split the build between windows and linux. This may be a challenge with goreleaser, but I haven't read the docs enough to know if I am just imagining the problem.

**Comment by LasneF** [comment]
@daveshanley  issue is reproducible on /openapi-changes_0.0.54

**Comment by daveshanley** [comment]
Fixed in `v0.0.60`
